# Default values for client.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: servicehub-mygreeterv3-client


command:
  - /client

args:
  - hello
  - --interval-milli-sec=60000
  - --json-log
  - --remote-addr=servicehub-mygreeterv3-server.servicehub-mygreeterv3-server:50051
  - --http-addr=http://servicehub-mygreeterv3-server.servicehub-mygreeterv3-server.svc.cluster.local:50061

# Info used for authorization policy
allowedPrincipals: []

allowedRequests: []
