# Default values for demoserver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: servicehub-mygreeterv3-demoserver


service:
  type: ClusterIP
  port: 50071

command:
  - /demoserver

args:
  - start
  - --json-log
  - --port=50071 

# Info used for authorization policy
allowedPrincipals: 
  - cluster.local/ns/servicehub-mygreeterv3-server/sa/servicehub-mygreeterv3-server


