{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "server.serviceAccountName" . }}
  namespace: {{ include "server.fullname" . }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
  annotations:
    {{- if and .Values.clientId .Values.clientId.value -}}
    {{- $newAnnotation := dict "azure.workload.identity/client-id" .Values.clientId.value -}}
    {{- $mergedAnnotations := merge .Values.serviceAccount.annotations $newAnnotation -}}
    {{- toYaml $mergedAnnotations | nindent 4 }}
    {{- else -}}
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
    {{- end }}
{{- end }}
